---
- name: Test junos security policies
  hosts: juniper1
  gather_facts: false
  vars:
    ansible_connection: netconf

  tasks:
    - name: Deploy security policies
      junipernetworks.junos.junos_security_policies:
        config:
          from_zones:
            - name: trust
              to_zones:
                - name: trust
                  policies:
                    - name: default-permit
                      match:
                        source_address:
                          any: true
                        destination_address:
                          any: true
                        application:
                          any: true
                - name: untrust
                  policies:
                    - name: default-permit
                      match:
                        source_address:
                          any: true
                        destination_address:
                          any: true
                        application:
                          any: true
                  then: 
                    deny: false
        state: merged