---
- name: Test junos security policies
  hosts: juniper1
  gather_facts: false
  vars:
    ansible_connection: netconf

  tasks:
    - name: Deploy security policies
      junipernetworks.junos.junos_security_policies:
        config:
          from_zones:
            - name: trust
              to_zones:
                - name: trust
                  policies:
                    - name: dns-permit-all
                      match:
                        source_address:
                          any: true
                        destination_address:
                          any: true
                        application:
                          names: junos-dns
                      then:
                        permit: true
                        log: session_init
        state: merged