---
- name: Test junos security policies
  hosts: juniper1
  gather_facts: false
  vars:
    ansible_connection: netconf
    
  tasks:
    - name: Get junos security policies configuration
      junipernetworks.junos.junos_security_policies:
        state: gathered
      register: state

    - name: Debug
      ansible.builtin.debug:
        var: state

  tasks:
    - name: Deploy security policies
      juniper-networks.junos.junos_security_policies:
        config:
          from_zones:
            - name: trust
              to_zones:
                - name: trust
                  policies:
                    - name: default-permit
                      match:
                        source_address:
                          any: true
                        destination_address:
                          any: true
                        application:
                          any: true
                - name: untrust
                  policies:
                    - name: default-permit
                      match:
                        source_address:
                          any: true
                        destination_address:
                          any: true
                        application:
                          any: true
        state: merged
          
    - name: Get junos security policies configuration
      junipernetworks.junos.junos_security_policies:
        state: gathered
      register: state
      
      
    - name: Results
      ansible.builtin.debug:
        var: state