---
- name: Configure Security Policy On a Firewall
  hosts: juniper1
  gather_facts: no

  tasks:
    - name: load configure lines into device
      junipernetworks.junos.junos_config:
        lines:
          - set security policies from-zone trust to-zone untrust policy 112 match source-address address1
        comment: update config

    - name: confirm a previous commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
