---
- name: This will set a Junos device hostname
  host: juniper1

  task: 

  - name: Set Junos device hostname to Blah
    junipernetworks.junos.junos_hostname:
      config:
        hostname: vSRX-1_Office_2
      state: merged
  