---
- name: Restore config from backup filename
  hosts: azure-vsrx
  gather_facts: no

  vars:
  - filename: "{{ config_name }}"
  #- update_type: "{{ update }}"

  tasks:

    - name: remove loaded config
      junipernetworks.junos.junos_config:
          lines: delete

    - name: load configure file into device
      junipernetworks.junos.junos_config:
        src: "{{ filename }}"
        src_format: set
        #update: "{{ update_type }}"
        confirm_commit: true