---
- name: Test junos security policies
  hosts: juniper1
  connection: local
  gather_facts: false

  tasks:
    - name: Deploy security policies
      junipernetworks.junos.junos_security_policies:
        config:
          from_zones:
            - name: trust
              to_zones:
                - name: untrust
                  policies:
                    - name: default-block-https
                      match:
                        source_address:
                          any: true
                        destination_address:
                          any: true
                        application:
                        - names: junos-https
                      then:
                        deny: false
                        log: session_init
        state: merged

