---
- name: RollBack To Previous Config
  hosts: azure-vsrx
  gather_facts: no

  vars:
    - number: "{{ rollback }}"

  tasks:

    - name: Perform Restore to Previous Config
      junipernetworks.junos.junos_config:
        rollback: "{{ number }}"
        confirm_commit: true
