---
- name: This Playbook allows you to run a command using the cmd var
  hosts: juniper1
  vars:
    command: "{{ cmd }}"

  tasks:

    - name: Run and Juniper show command
      junipernetworks.junos.junos_command:
        commands: show "{{ command }}"
      register: results

    - name: display results
      debug:
        var: results.stdout_lines    