---
- name: Apply Config to an Junos Device
  hosts: azure-vsrx
  gather_facts: no

  vars:
    - filepath: "{{ filepath }}"

  tasks:
    - name: load configure lines into device
      junipernetworks.junos.junos_config:
        src: "{{ filepath }}"
        src_format: set
        update: merge

    - name: display what config has been recently applied
      junipernetworks.junos.junos_config:
        lines:
          - show | compare rollback 1
        register: result

    - name: Display Recently Appliced Config
      debug:
        var: result.stdout_lines