---
- name: Restore config from backup filename
  hosts: azure-vsrx
  gather_facts: no

  vars:
  #- filename: "{{ config_name }}"
  #- update_type: "{{ update }}"

  tasks:

    - name: remove loaded config
      junipernetworks.junos.junos_config:
          lines:
            - load set srx.cfg
          comment: loaded from backup cfg

