---
- name: This will set a Junos device hostname
  host: azure-vsrx

  task: 

  - name: Set Junos device hostname to Blah
    junipernetworks.junos.junos_hostname:
      config:
        hostname: Azure-vSRX-#1
      state: merged
  