---
- name: Run Show Interfaces Command
  hosts: azure-vsrx
  gather_facts: no

  tasks:

  - name: run multiple commands on remote nodes
    junipernetworks.junos.junos_command:
      commands: show interfaces
    register: result

  - name: display output
    debug:
      var: result.stdout_lines