---
- name: Apply Config to an Junos Device
  hosts: azure-vsrx
  gather_facts: no

  vars:
    - filepath: "{{ filepath }}"

  tasks:
    - name: load configure lines into device
      junipernetworks.junos.junos_config:
        src: "{{ filepath }}"
        src_format: set
        update: merge
