---
- name: Configure Security Policy On a Firewall
  hosts: juniper1
  connection: local
  gather_facts: no

  tasks:

    - name: Configure a Secuirty Policy on a Firewall
      junipernetworks.junos.junos_security_policies:
        config:
          from_zones:
            name: trust
              to_zones:
                name: untrust
                policies:
                  description:
                  match:
                    application:
                      names: junos-http
                    destination_address:
                      addresses: address1
                    from_zone:
                      names: trust
                    source_address:
                      names: address2
                    to_zone:
                      names: untrust
                  name: test_http
                  then:
                    count: true
                    deny: false
                    log: session_init
        state: merged
