---
- name: Apply Config to an Junos Device
  hosts: juniper1
  gather_facts: no

  tasks:
    - name: load configure lines into device
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces ge-0/0/1 unit 0 description "Test interface"
          - set vlans vlan01 description "Test vlan"
        comment: update config
