---
- name: RollBack To Previous Config
  hosts: azure-vsrx
  gather_facts: no

  tasks:

    - name: Perform Restore to Previous Config
      junipernetworks.junos.junos_config:
        rollback: 2
        confirm_commit: true
