---
- name: Apply Config to an Junos Device
  hosts: azure-vsrx
  gather_facts: no

  tasks:
    - name: load configure lines into device
      junipernetworks.junos.junos_config:
        src: "files/config.txt"
        src_format: set
        comment: update config
        update: merge
