---
- name: Apply Config to an Junos Device
  hosts: juniper1
  gather_facts: no

  tasks:
    - name: load configure lines into device
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces fxp0 unit 0 description mgmt_interface
        comment: update config
