---
- name: Configure Security Policy On a Firewall
  hosts: juniper1
  connection: local
  gather_facts: no

  tasks:

    - name: Configure a Secuirty Policy on a Firewall
      junipernetworks.junos.junos_security_policies:
        config:
          polices:
            - description: test policy
            - match:
                application:
                  names:
                    - junos-http
                destination_address:
                  addresses: address1
                from_zone:
                  names:
                    - trust
                source_address:
                  addresses: address2
                to_zone:
                  names:
                    - untrust
              name: test_policy
              then:
                count: true
                deny: false
                log: session_close
                
