---
- name: Run Show Interfaces Command
  hosts: azure-vsrx
  gather_facts: no

  tasks:

  - name: run multiple commands on remote nodes
    junipernetworks.junos.junos_command:
      commands: 
        - show configuration 
      display: json
      dest_dir: "{{ playbook_dir }}"