---
- name: Run a restore using a backup filename
  hosts: azure-vsrx
  gather_facts: no

  tasks:

    - name: Create restore job template
      ansible.controller.job_template:
        name: "Network Automation - Restore"
        job_type: "run"
        inventory: "{{ restore_inventory | default('Demo Inventory') }}"
        project: "{{ restore_project | default('Network Demo') }}"
        playbook: "{{ restores_playbook | default('playbooks/network_restore.yml') }}"
        credential: "{{ restore_credential | default('Network Credential') }}"
        survey_enabled: true
        #survey_spec: "{{ lookup('template', '{{ playbook_dir }}/templates/backup.j2') }}"
        validate_certs: false
        execution_environment: "Default execution environment"
      run_once: true