---
- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Change Admin Password
      paloaltonetworks.panos.panos_administrator:
        provider: "{{ device }}"
        #admin_username: 
        admin_password: "{{ default_admin_password }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new Admin Account
      paloaltonetworks.panos.panos_administrator:
        provider: "{{ device }}"
        admin_username: "{{ new_admin_username }}"
        admin_password: "{{ new_admin_password }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create Management Profile
      paloaltonetworks.panos.panos_mgtconfig:
        provider: "{{ device }}"
        hostname: "{{ device_hostname }}"
        domain: "{{ device_domain }}"
        dns_server_primary: "{{ device_dns_primary }}"
        dns_server_secondary: "{{ device_dns_secondary }}"
        login_banner: "{{ device_login_banner }}"
        ntp_server_primary: "{{ device_ntp_primary }}"
        ntp_server_secondary: "{{ device_ntp_secondary }}"
        panorama_primary: "{{ device_panorama_primary }}"
        panorama_secondary: "{{ device_panorama_secondary }}"
        timezone: "{{ device_timezone }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new Syslog profile
      paloaltonetworks.panos.panos_syslog_profile:
       provider: "{{ device }}"
       name: "{{ device_syslog_profile_name }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new Syslog Server
      paloaltonetworks.panos.panos_syslog_server:
        provider: "{{ device }}"
        facility: "{{ device_syslog_facility }}"
        format: "{{ device_syslog_format }}"
        name: "{{ device_syslog_name }}"
        server: "{{ device_syslog_server }}"
        syslog_port: "{{ device_syslog_syslog_port }}"
        syslog_profile: "{{ device_syslog_syslog_profile }}"
        transport: "{{ device_syslog_transport }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new Interface
      paloaltonetworks.panos.panos_interface:
        provider: "{{ device }}"
        comment: "{{ device_interface_comment }}"
        if_name: "{{ device_interface_if_name }}"
        link_duplex: "{{ device_interface_link_duplex }}"
        link_speed: "{{ device_interface_link_speed }}"
        link_state: "{{ device_interface_link_state }}"
        #management_profile: "{{ device_interface_mgmt_profile }}"
        mode: "{{ device_interface_mode }}"
        #vr_name: "{{ device_interface_vr_name }}"
        #zone_name: "{{ device_interface_zone_name }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new Zone
      paloaltonetworks.panos.panos_zone:
        provider: "{{ device }}"
        interface: "{{ device_zone_interface }}"
        #log_setting: "{{ device_zone_log_setting }}"
        mode: "{{ device_zone_mode }}"
        zone: "{{ device_zone_name }}"
        #zone_profile: "{{ device_zone_profile }}"

- name: Apply Configurations to Firewall
  hosts: "azure-paloalto-2"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
  - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new management profile
      paloaltonetworks.panos.panos_management_profile:
        provider: "{{ device }}"
        name: "{{ device_mgmt_profile_name }}"
        https: "{{ device_mgmt_profile_https }}"
        permitted_ip: "{{ device_mgmt_profile_permitted_ip }}"
        ping : "{{ device_mgmt_profile_ping }}"
        snmp: "{{ device_mgmt_profile_snmp }}"


  

