---
- name: Create Super User
  hosts: "firewall"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create new Super User
      paloaltonetworks.panos.panos_admin:
        admin_username: ansible
        admin_password: PaloAlto1!
        superuser: true
        