---
- name: Create Address Object from a CSV Source File
  hosts: "firewall"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

    csv_filename: "csv/address.csv"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Read CSV file
      ansible.builtin.read_csv:
        path: "{{ csv_filename }}"
        key: hostname
      register: csv_data

    - name: Create address objects
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ item.value.hostname }}"
        value: "{{ item.value.ip }}"
      with_items: "{{ csv_data.dict | dict2items }}"

    - name: Create a list of the address objects
      ansible.builtin.set_fact:
        address_objects_list: "{{ csv_data.dict | dict2items | map(attribute='key') | list }}"

    - name: Add address objects to address group
      paloaltonetworks.panos.panos_address_group:
        provider: "{{ device }}"
        name: test_group
        static_value: "{{ address_objects_list }}"