---
- name: Create address objects
  hosts: "firewall"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
    - vars/objects.yml
    - vars/services.yml
    
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create source address object "{{ hostname_source }}"
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ hostname_source }}"
        value: "{{ source_address }}"
        description: "{{ source_description }}"

    - name: Create destination address object "{{ hostname_destination }}"
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ hostname_destination }}"
        value: "{{ destination_address }}"
        description: "{{ destination_description }}"

  tasks:
    - name: Create service object "{{ service_name }}"
      paloaltonetworks.panos.panos_service_object:
        provider: "{{ device }}"
        name: "{{ service_name }}"
        protocol: "{{ service_protocol }}"
        destination_port: "{{ service_destination_port }}"
        description: "{{ service_description }}"