---
- name: Get Facts about the PANOS Device
  hosts: paloalto1
  connection: local

  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: '{{ device }}'

    - name: Display model, PAN-OS version
      ansible.builtin.debug:
        msg: "Model: {{ ansible_facts['net_model'] }}, version: {{ ansible_facts['net_version'] }}"