---
- name: Commit firewall candidate configuration
  hosts: firewall
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Commit candidate configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ device }}"
      register: results
    - debug:
        msg: "Commit with Job ID: {{ results.jobid }} had output: {{ results.details }}"

    - name: Send Email notification
      community.general.mail: 
        host: smtp.gmail.com
        port: 587
        username: adamgb116@gmail.com
        password: vkby bxnf ckvr bvzq
        to: adamgb116@gmail.com
        subject: "Commit with Job ID: {{ results.jobid }} had output: {{ results.details }}"
        body: "Commit with Job ID: {{ results.jobid }} had output: {{ results.details }}"
        secure: starttls
      delegate_to: localhost
