---
- name: Create Address Object from a CSV Source File
  hosts: firewall
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

    csv_filename: "{{ address_csv }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Read CSV file
      ansible.builtin.read_csv:
        path: "{{ csv_filename }}"
        key: hostname
      register: csv_data

    - name: Create address objects from {{ address_csv }}
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ item.value.hostname }}"
        value: "{{ item.value.ip_address }}"
      with_items: "{{ csv_data.dict | dict2items }}"