---
- name: Gather Object Facts
  hosts: firewall
  connection: local
  ignore_errors: true
  #gather_facts: yes

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
    - "{{ location }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create Security Policy for Request {{ location }}
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        device_group: "{{ device_group | default(omit) }}"
        rule_name: "{{ rule_name | mandatory }}"
        description: "{{ description | mandatory }}"
        tag_name: "{{ tag_name | default(omit) }}"
        source_zone: "{{ source_zone | mandatory }}"
        source_ip: "{{ source_ip | mandatory }}"
        destination_zone: "{{ destination_zone | mandatory }}"
        destination_ip: "{{ destination_ip | mandatory }}"
        application: "{{ application | default(omit) }}"
        service: "{{ service | default(omit) }}"
        action: "{{ action_commit | mandatory }}"

    - name: Send Email notification
      community.general.mail: 
        host: send.xtra.co.nz
        port: 587
        username: a.gallen.brydon@xtra.co.nz
        password: today98
        to: "{{ notification_email_address | default(omit) }}"
        subject: Ansible Report
        body: Your "{{ location }}" has been completed
        secure: try
      delegate_to: localhost