---
- name: Create Service Objects from a CSV Source File
  hosts: firewall
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

    csv_filename: "{{ service_csv }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Read CSV file
      ansible.builtin.read_csv:
        path: "{{ csv_filename }}"
        key: name
      register: csv_data

    - name: Create address objects {{ service_csv }}
      paloaltonetworks.panos.panos_service_object:
        provider: "{{ device }}"
        name: "{{ item.value.name }}"
        protocol: "{{ item.value.protocol }}"
        destination_port: "{{ item.value.destination_port }}"
      with_items: "{{ csv_data.dict | dict2items }}"