---
- name: Gather Object Facts
  hosts: firewall
  connection: local
  ignore_errors: true
  #gather_facts: yes

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_prompt:
    - name: source_ip_new_name
      prompt: New Device - Please create a new object - Enter in object name 'server-001_ip-address'
      private: false

    - name: source_ip_new_type
      prompt: Enter type of Object ip-netmask(default), ip-range, fqdn
      default: ip-netmask

    - name: source_ip_new_value
      prompt: Enter the IP address of the object e.g 10.10.10.10/32 or 10.10.10.0/28 if ip-range
      private: false

    - name: source_ip_new_description
      prompt: Enter a description of this object
      private: false

    - name: destination_ip_new_name
      prompt: New Device - Please create a new object - Enter in object name 'server-001_ip-address'
      private: false

    - name: destination_ip_new_type
      prompt: Enter type of Object ip-netmask(default), ip-range, fqdn
      default: ip-netmask

    - name: destination_ip_new_value
      prompt: Enter the IP address of the object e.g 10.10.10.10/32 or 10.10.10.0/28 if ip-range
      private: false

    - name: destination_ip_new_description
      prompt: Enter a description of this object
      private: false

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create Address Object New Source
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ item.value.source_ip_new_name | default(omit) }}"
        address_type: "{{ item.value.source_ip_new_type | default(omit) }}"
        value: "{{ item.value.source_ip_new_value | default(omit) }}"
        description: "{{ item.value.source_ip_new_description | default(omit) }}"
      with_items: "{{ source_ip_new_name.dict | source_ip_new_value.dict |  source_ip_new_value | source_ip_new_description | dict2items }}"
