---
- name: Create address objects
  hosts: "firewall"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files:
    - vars/objects.yml

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create source address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ hostname_source }}"
        value: "{{ source_address }}"
        description: "{{ source_description }}"

    - name: Create destination address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ hostname_destination }}"
        value: "{{ destination_address }}"
        description: "{{ destination_description }}"
