---
- name: Gather system info
  hosts: azure-firewall
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        # config, system, session, vr, vsys, ha, interface
        gather_subset: ['system']
      register: outputs

    - name: Display information
      ansible.builtin.debug:
        msg: "{{ outputs }}"