---
- name: Gather Object Facts
  hosts: azure-firewall
  connection: local
  gather_facts: yes

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_prompt:

    - name: name
      prompt: Enter In the Name of the Object 
      
    - name: object_type
      prompt: Please Enter Object Type - Address(default), address-group, application, application-group, service, service-group
      default: address

  collections:
    - paloaltonetworks.panos

    - name: Gather Object Facts
      paloaltonetworks.panos.panos_object_facts:
        provider: "{{ device }}"
        device_group: "{{ device_group | default(omit) }}"
        name: "{{ name | mandatory }}"
        name_regex: "{{ name_regex | default(omit) }}"
        object_type: "{{ object_type | mandatory }}"
        field: "{{ field | default(omit) }}"
        field_search_type: "{{ field_search_type | default(omit) }}"
        field_search_value: "{{ field_search_value | default(omit) }}"
      register: outputs

    - name: Display information
      ansible.builtin.debug:
        msg: "{{ outputs }}"