---
- name: Gather Object Facts
  hosts: azure-firewall
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  vars_files: 
    - vars/ipaddress.yml

  collections:
    - paloaltonetworks.panos

  tasks: 
    - name: Validate if {{ source_ip_address }} is a valid within any zone on the firewall {{ hostname }}
      ansible.builtin.set_fact:
        data: "{{ '{{ source_ip_address }}' is ansible.utils.in_network '10.100.0.0/22' }}"