---
- name: Dislay the configuration of the Firewall
  hosts: juniper1
  vars:
    - output: "{{ output_type }}"


  tasks:
  - name: Gather Facts of the Firewall
    junipernetworks.junos.junos_facts:
      gather_subset: config
      config_format: "{{ output }}"
    register: results

  - name: display results
    debug:
      var: results.stdout_lines 