---
- name: Run Show Interfaces Command
  hosts: juniper1
  gather_facts: False

  tasks:

  - name: run multiple commands on remote nodes
    junipernetworks.junos.junos_command:
      commands: show interfaces
    register: result

  - name: display output
    debug:
      var: result.stdout_lines